# Generated by Django 2.2.1 on 2019-11-07 18:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('media', models.FileField(upload_to='projects/')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('goal', models.CharField(max_length=300)),
                ('proj_type', models.CharField(choices=[('RD', 'Research & Development'), ('PJ', 'Improvement Project'), ('CS', 'Custom Variation')], default='RD', max_length=3)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=40)),
                ('justification', models.CharField(max_length=300)),
                ('shall', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('value_type', models.CharField(choices=[('BOO', 'True or False'), ('LESS', 'Less Than'), ('MORE', 'More Than'), ('RANGE', 'Between')], default='LESS', max_length=5)),
                ('goal_value', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField()),
                ('requirements', models.ManyToManyField(to='projects.Requirement', verbose_name='Satisfies Requirement(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Concept')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('content', models.CharField(max_length=300)),
                ('stage', models.CharField(choices=[('RQ', 'Requirements/Specifications'), ('CON', 'Concept Design'), ('PT', 'Construction/Prototype')], default='RQ', max_length=3)),
                ('resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
