# Generated by Django 2.2.1 on 2019-11-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='requirements',
            field=models.ManyToManyField(related_name='requirements', to='projects.Requirement', verbose_name='Satisfies Requirement(s)'),
        ),
    ]
