# Generated by Django 2.1.1 on 2019-05-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('part_description', models.CharField(max_length=30)),
                ('has_drawing', models.BooleanField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
