# Generated by Django 2.2.1 on 2019-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_remove_part_has_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
