# Generated by Django 2.2.1 on 2019-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20190606_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='drawing_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='in_syteline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='notes',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
