# Generated by Django 2.2.1 on 2019-10-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20191024_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
