# Generated by Django 2.2.1 on 2019-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20191024_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='in_syteline',
            field=models.BooleanField(default=False),
        ),
    ]
