# Generated by Django 2.2.1 on 2019-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20191024_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_description',
            field=models.CharField(max_length=200),
        ),
    ]
