# Generated by Django 2.2.6 on 2019-12-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_auto_20191024_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='controled',
            field=models.BooleanField(default=False),
        ),
    ]
