# Generated by Django 2.1.1 on 2019-05-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECO',
            fields=[
                ('ECO_number', models.AutoField(primary_key=True, serialize=False, verbose_name='ECO Number')),
            ],
        ),
        migrations.CreateModel(
            name='ECR',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('ECR_number', models.AutoField(primary_key=True, serialize=False, verbose_name='ECR Number')),
                ('requested_change', models.CharField(max_length=300, verbose_name='Requested Change or Improvement')),
                ('justification', models.CharField(max_length=300, verbose_name='Justification')),
                ('solution', models.CharField(max_length=300, verbose_name='Solution & Cost')),
                ('requirements', models.CharField(max_length=300)),
                ('impact', models.CharField(max_length=300)),
                ('steps', models.CharField(max_length=300)),
                ('remediation', models.CharField(max_length=300)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part_numbers', models.ManyToManyField(to='parts.Part', verbose_name='Affected Part Numbers')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_level', models.CharField(max_length=1, verbose_name='Revision')),
                ('description', models.CharField(max_length=100, verbose_name='Change Description')),
                ('ECO_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='changes.ECO', verbose_name='Related ECO Number')),
                ('revised_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Part', verbose_name='Affected Drawings')),
            ],
        ),
        migrations.AddField(
            model_name='eco',
            name='ECR_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changes.ECR', verbose_name='Related ECR'),
        ),
        migrations.AddField(
            model_name='eco',
            name='part_numbers',
            field=models.ManyToManyField(to='parts.Part', verbose_name='Affected Part Numbers'),
        ),
    ]
