# Generated by Django 2.1.1 on 2019-05-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0005_auto_20190505_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='eco_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
