# Generated by Django 2.1.1 on 2019-05-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0006_eco_eco_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecr',
            name='ecr_disposition',
            field=models.CharField(blank=True, choices=[('WNF', 'Will Not Fix'), ('FX', 'Fixed'), ('ECO', 'Create ECO'), ('NT', 'No Trouble Found')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='status',
            field=models.CharField(choices=[('OH', 'On Hold'), ('CL', 'Closed'), ('IP', 'In Progress')], default='IP', max_length=3),
        ),
    ]
