# Generated by Django 2.1.1 on 2019-05-13 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changes', '0007_auto_20190510_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecr',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ECR', to=settings.AUTH_USER_MODEL),
        ),
    ]
