# Generated by Django 2.1.1 on 2019-05-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0008_ecr_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='oa_status',
            field=models.CharField(default='Created', max_length=30),
        ),
    ]
