# Generated by Django 2.1.1 on 2019-05-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0009_eco_oa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecr',
            name='status',
            field=models.CharField(choices=[('OH', 'On Hold'), ('CL', 'Closed'), ('IP', 'In Progress'), ('OP', 'Open')], default='IP', max_length=3),
        ),
    ]
