# Generated by Django 2.1.1 on 2019-05-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0011_auto_20190516_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecr',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('2', 'Medium'), ('1', 'High')], default='1', max_length=3),
        ),
    ]
