# Generated by Django 2.1.1 on 2019-05-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0012_auto_20190516_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('1', 'High'), ('3', 'Low')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('1', 'High'), ('3', 'Low')], default='1', max_length=3),
        ),
    ]
