# Generated by Django 2.1.1 on 2019-05-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0013_auto_20190517_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecr',
            name='justification',
        ),
        migrations.AlterField(
            model_name='eco',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('1', 'High'), ('2', 'Medium')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('1', 'High'), ('2', 'Medium')], default='1', max_length=3),
        ),
    ]
