# Generated by Django 2.1.1 on 2019-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0014_auto_20190517_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eco',
            name='eng_sign',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eco',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('3', 'Low'), ('2', 'Medium')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='ecr_disposition',
            field=models.CharField(blank=True, choices=[('NA', '------'), ('WNF', 'Will Not Fix'), ('FX', 'Fixed'), ('ECO', 'Create ECO'), ('NT', 'No Trouble Found')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('3', 'Low'), ('2', 'Medium')], default='1', max_length=3),
        ),
    ]
