# Generated by Django 2.2.1 on 2019-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0017_auto_20190529_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eco',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('3', 'Low'), ('1', 'High')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('3', 'Low'), ('1', 'High')], default='1', max_length=3),
        ),
    ]
