# Generated by Django 2.2.1 on 2019-06-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0023_auto_20190606_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eco',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('1', 'High'), ('3', 'Low')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='impact',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('1', 'High'), ('3', 'Low')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='remediation',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='requested_change',
            field=models.CharField(default='N/A', max_length=300, verbose_name='Requested Change or Improvement'),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='requirements',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='steps',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
