# Generated by Django 2.2.1 on 2019-10-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0026_auto_20191024_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eco',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('3', 'Low'), ('1', 'High')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('3', 'Low'), ('1', 'High')], default='1', max_length=3),
        ),
    ]
