# Generated by Django 2.2.1 on 2019-11-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changes', '0031_auto_20191028_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='ecr',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='ecr',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='ecr',
            name='remediation',
        ),
        migrations.RemoveField(
            model_name='ecr',
            name='requested_change',
        ),
        migrations.RemoveField(
            model_name='ecr',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='ecr',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='ecr',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='ECO_number',
        ),
        migrations.AddField(
            model_name='revision',
            name='ECR_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='changes.ECR', verbose_name='Related ECR Number'),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('3', 'Low'), ('1', 'High')], default='1', max_length=3),
        ),
        migrations.DeleteModel(
            name='ECO',
        ),
        migrations.AddField(
            model_name='notes',
            name='ecr_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='changes.ECR', verbose_name='Related ECR Number'),
        ),
    ]
