# Generated by Django 2.2.1 on 2019-11-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0032_auto_20191106_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecr',
            name='part_numbers',
            field=models.ManyToManyField(blank=True, to='parts.Part', verbose_name='Affected Part Numbers'),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('3', 'Low'), ('2', 'Medium')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='ecr',
            name='status',
            field=models.CharField(choices=[('OH', 'On Hold'), ('CL', 'Closed'), ('IP', 'In Progress'), ('OP', 'Open')], default='OP', max_length=3),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
    ]
