# Generated by Django 2.2.1 on 2019-12-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0033_auto_20191107_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('1', 'High'), ('2', 'Medium')], default='1', max_length=3),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='Attachment Title')),
                ('file', models.FileField(upload_to='attachments/')),
                ('ECR_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='changes.ECR', verbose_name='Related ECR Number')),
            ],
        ),
    ]
