# Generated by Django 2.2.6 on 2019-12-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0034_auto_20191202_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecr',
            name='priority',
            field=models.CharField(choices=[('2', 'Medium'), ('3', 'Low'), ('1', 'High')], default='1', max_length=3),
        ),
    ]
